application: cmoanderic
version: master-0x2x2
runtime: python27
api_version: 1
threadsafe: true


default_expiration: "10m"


libraries:
- name: webapp2
  version: "latest"


handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /(\w+\.html)
  static_files: html/\1
  upload: html/(.*\.html)

- url: /(\w+)/?
  static_files: html/\1/index.html
  upload: html/(.*)/index.html

- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?service-account\.json$
- ^(.*/)?service-account\.json\.enc$
- ^(.*/)?requirements\.txt$
- ^(.*/)?README\.md$
